spring:
  application:
    name: data-collector-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

api:
  crypto:
    key: ${CRYPTO_API_KEY:CG-NBNxC1kS9g3obDn2ta7eGFdk}
    url: https://api.coingecko.com/api/v3

server:
  port: 8083

logging:
  level:
    com.smartalert.datacollector: DEBUG
